# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import anbp_pb2 as anbp__pb2


class GreeterStub(object):
    """创建服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ANBP = channel.unary_unary(
                '/pyserver.Greeter/ANBP',
                request_serializer=anbp__pb2.BPRequest.SerializeToString,
                response_deserializer=anbp__pb2.BPReply.FromString,
                )


class GreeterServicer(object):
    """创建服务
    """

    def ANBP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ANBP': grpc.unary_unary_rpc_method_handler(
                    servicer.ANBP,
                    request_deserializer=anbp__pb2.BPRequest.FromString,
                    response_serializer=anbp__pb2.BPReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pyserver.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """创建服务
    """

    @staticmethod
    def ANBP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pyserver.Greeter/ANBP',
            anbp__pb2.BPRequest.SerializeToString,
            anbp__pb2.BPReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
