# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anbp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='anbp.proto',
  package='pyserver',
  syntax='proto3',
  serialized_options=b'\n\023org.jpdna.grpchelloB\rPyServerProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nanbp.proto\x12\x08pyserver\"v\n\tBPRequest\x12\x10\n\x08userInfo\x18\x01 \x01(\t\x12\x0f\n\x07oStatus\x18\x02 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x03 \x01(\t\x12\x13\n\x0bpreReportBP\x18\x04 \x01(\t\x12\x1f\n\x17preReportTimeDiffMinute\x18\x05 \x01(\t\"D\n\x07\x42PReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0e\x62loodPpressure\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t2;\n\x07Greeter\x12\x30\n\x04\x41NBP\x12\x13.pyserver.BPRequest\x1a\x11.pyserver.BPReply\"\x00\x42&\n\x13org.jpdna.grpchelloB\rPyServerProtoP\x01\x62\x06proto3'
)




_BPREQUEST = _descriptor.Descriptor(
  name='BPRequest',
  full_name='pyserver.BPRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userInfo', full_name='pyserver.BPRequest.userInfo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='oStatus', full_name='pyserver.BPRequest.oStatus', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='features', full_name='pyserver.BPRequest.features', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preReportBP', full_name='pyserver.BPRequest.preReportBP', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preReportTimeDiffMinute', full_name='pyserver.BPRequest.preReportTimeDiffMinute', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=142,
)


_BPREPLY = _descriptor.Descriptor(
  name='BPReply',
  full_name='pyserver.BPReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pyserver.BPReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bloodPpressure', full_name='pyserver.BPReply.bloodPpressure', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='pyserver.BPReply.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=212,
)

DESCRIPTOR.message_types_by_name['BPRequest'] = _BPREQUEST
DESCRIPTOR.message_types_by_name['BPReply'] = _BPREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BPRequest = _reflection.GeneratedProtocolMessageType('BPRequest', (_message.Message,), {
  'DESCRIPTOR' : _BPREQUEST,
  '__module__' : 'anbp_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.BPRequest)
  })
_sym_db.RegisterMessage(BPRequest)

BPReply = _reflection.GeneratedProtocolMessageType('BPReply', (_message.Message,), {
  'DESCRIPTOR' : _BPREPLY,
  '__module__' : 'anbp_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.BPReply)
  })
_sym_db.RegisterMessage(BPReply)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='pyserver.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=214,
  serialized_end=273,
  methods=[
  _descriptor.MethodDescriptor(
    name='ANBP',
    full_name='pyserver.Greeter.ANBP',
    index=0,
    containing_service=None,
    input_type=_BPREQUEST,
    output_type=_BPREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
