# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anbpOptimizer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='anbpOptimizer.proto',
  package='pyserver',
  syntax='proto3',
  serialized_options=b'\n\023org.jpdna.grpchelloB\rPyServerProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x61nbpOptimizer.proto\x12\x08pyserver\";\n\x12OptimizerBPRequest\x12\x12\n\nwearUserId\x18\x01 \x01(\t\x12\x11\n\toptStatus\x18\x02 \x01(\t\"\"\n\x10OptimizerBPReply\x12\x0e\n\x06status\x18\x01 \x01(\t2V\n\x10OptimizerGreeter\x12\x42\n\x04\x41NBP\x12\x1c.pyserver.OptimizerBPRequest\x1a\x1a.pyserver.OptimizerBPReply\"\x00\x42&\n\x13org.jpdna.grpchelloB\rPyServerProtoP\x01\x62\x06proto3'
)




_OPTIMIZERBPREQUEST = _descriptor.Descriptor(
  name='OptimizerBPRequest',
  full_name='pyserver.OptimizerBPRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wearUserId', full_name='pyserver.OptimizerBPRequest.wearUserId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='optStatus', full_name='pyserver.OptimizerBPRequest.optStatus', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=92,
)


_OPTIMIZERBPREPLY = _descriptor.Descriptor(
  name='OptimizerBPReply',
  full_name='pyserver.OptimizerBPReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pyserver.OptimizerBPReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['OptimizerBPRequest'] = _OPTIMIZERBPREQUEST
DESCRIPTOR.message_types_by_name['OptimizerBPReply'] = _OPTIMIZERBPREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OptimizerBPRequest = _reflection.GeneratedProtocolMessageType('OptimizerBPRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPTIMIZERBPREQUEST,
  '__module__' : 'anbpOptimizer_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.OptimizerBPRequest)
  })
_sym_db.RegisterMessage(OptimizerBPRequest)

OptimizerBPReply = _reflection.GeneratedProtocolMessageType('OptimizerBPReply', (_message.Message,), {
  'DESCRIPTOR' : _OPTIMIZERBPREPLY,
  '__module__' : 'anbpOptimizer_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.OptimizerBPReply)
  })
_sym_db.RegisterMessage(OptimizerBPReply)


DESCRIPTOR._options = None

_OPTIMIZERGREETER = _descriptor.ServiceDescriptor(
  name='OptimizerGreeter',
  full_name='pyserver.OptimizerGreeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=130,
  serialized_end=216,
  methods=[
  _descriptor.MethodDescriptor(
    name='ANBP',
    full_name='pyserver.OptimizerGreeter.ANBP',
    index=0,
    containing_service=None,
    input_type=_OPTIMIZERBPREQUEST,
    output_type=_OPTIMIZERBPREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OPTIMIZERGREETER)

DESCRIPTOR.services_by_name['OptimizerGreeter'] = _OPTIMIZERGREETER

# @@protoc_insertion_point(module_scope)
